export const comments = [
  { id: 1, author: "John", text: "Крутой пост!" },
  { id: 2, author: "Jane", text: "Согласен с тобой!" },
  { id: 3, author: "Bob", text: "Отличная статья!" },
  { id: 4, author: "Bob", text: "Отличная статья!" },
  { id: 5, author: "Bob", text: "Отличная статья!" },
  { id: 6, author: "Bob", text: "Отличная статья!" },
  { id: 7, author: "Bob", text: "Отличная статья!" },
  { id: 8, author: "Bob", text: "Отличная статья!" },
  { id: 9, author: "Bob", text: "Отличная статья!" },
  { id: 1, author: "John", text: "Крутой пост!" },
  { id: 2, author: "Jane", text: "Согласен с тобой!" },
  { id: 3, author: "Bob", text: "Отличная статья!" },
  { id: 4, author: "Bob", text: "Отличная статья!" },
  { id: 5, author: "Bob", text: "Отличная статья!" },
  { id: 6, author: "Bob", text: "Отличная статья!" },
  { id: 7, author: "Bob", text: "Отличная статья!" },
  { id: 8, author: "Bob", text: "Отличная статья!" },
  { id: 9, author: "Bob", text: "Отличная статья!" },
  { id: 1, author: "John", text: "Крутой пост!" },
  { id: 2, author: "Jane", text: "Согласен с тобой!" },
  { id: 3, author: "Bob", text: "Отличная статья!" },
  { id: 4, author: "Bob", text: "Отличная статья!" },
  { id: 5, author: "Bob", text: "Отличная статья!" },
  { id: 6, author: "Bob", text: "Отличная статья!" },
  { id: 7, author: "Bob", text: "Отличная статья!" },
  { id: 8, author: "Bob", text: "Отличная статья!" },
  { id: 9, author: "Bob", text: "Отличная статья!" },
  { id: 1, author: "John", text: "Крутой пост!" },
  { id: 2, author: "Jane", text: "Согласен с тобой!" },
  { id: 3, author: "Bob", text: "Отличная статья!" },
  { id: 4, author: "Bob", text: "Отличная статья!" },
  { id: 5, author: "Bob", text: "Отличная статья!" },
  { id: 6, author: "Bob", text: "Отличная статья!" },
  { id: 7, author: "Bob", text: "Отличная статья!" },
  { id: 8, author: "Bob", text: "Отличная статья!" },
  { id: 9, author: "Bob", text: "Отличная статья!" },
  { id: 1, author: "John", text: "Крутой пост!" },
  { id: 2, author: "Jane", text: "Согласен с тобой!" },
  { id: 3, author: "Bob", text: "Отличная статья!" },
  { id: 4, author: "Bob", text: "Отличная статья!" },
  { id: 5, author: "Bob", text: "Отличная статья!" },
  { id: 6, author: "Bob", text: "Отличная статья!" },
  { id: 7, author: "Bob", text: "Отличная статья!" },
  { id: 8, author: "Bob", text: "Отличная статья!" },
  { id: 9, author: "Bob", text: "Отличная статья!" },
  { id: 1, author: "John", text: "Крутой пост!" },
  { id: 2, author: "Jane", text: "Согласен с тобой!" },
  { id: 3, author: "Bob", text: "Отличная статья!" },
  { id: 4, author: "Bob", text: "Отличная статья!" },
  { id: 5, author: "Bob", text: "Отличная статья!" },
  { id: 6, author: "Bob", text: "Отличная статья!" },
  { id: 7, author: "Bob", text: "Отличная статья!" },
  { id: 8, author: "Bob", text: "Отличная статья!" },
  { id: 9, author: "Bob", text: "Отличная статья!" },
  { id: 1, author: "John", text: "Крутой пост!" },
  { id: 2, author: "Jane", text: "Согласен с тобой!" },
  { id: 3, author: "Bob", text: "Отличная статья!" },
  { id: 4, author: "Bob", text: "Отличная статья!" },
  { id: 5, author: "Bob", text: "Отличная статья!" },
  { id: 6, author: "Bob", text: "Отличная статья!" },
  { id: 7, author: "Bob", text: "Отличная статья!" },
  { id: 8, author: "Bob", text: "Отличная статья!" },
  { id: 9, author: "Bob", text: "Отличная статья!" },
  { id: 1, author: "John", text: "Крутой пост!" },
  { id: 2, author: "Jane", text: "Согласен с тобой!" },
  { id: 3, author: "Bob", text: "Отличная статья!" },
  { id: 4, author: "Bob", text: "Отличная статья!" },
  { id: 5, author: "Bob", text: "Отличная статья!" },
  { id: 6, author: "Bob", text: "Отличная статья!" },
  { id: 7, author: "Bob", text: "Отличная статья!" },
  { id: 8, author: "Bob", text: "Отличная статья!" },
  { id: 9, author: "Bob", text: "Отличная статья!" },
  { id: 1, author: "John", text: "Крутой пост!" },
  { id: 2, author: "Jane", text: "Согласен с тобой!" },
  { id: 3, author: "Bob", text: "Отличная статья!" },
  { id: 4, author: "Bob", text: "Отличная статья!" },
  { id: 5, author: "Bob", text: "Отличная статья!" },
  { id: 6, author: "Bob", text: "Отличная статья!" },
  { id: 7, author: "Bob", text: "Отличная статья!" },
  { id: 8, author: "Bob", text: "Отличная статья!" },
  { id: 9, author: "Bob", text: "Отличная статья!" },
  { id: 1, author: "John", text: "Крутой пост!" },
  { id: 2, author: "Jane", text: "Согласен с тобой!" },
  { id: 3, author: "Bob", text: "Отличная статья!" },
  { id: 4, author: "Bob", text: "Отличная статья!" },
  { id: 5, author: "Bob", text: "Отличная статья!" },
  { id: 6, author: "Bob", text: "Отличная статья!" },
  { id: 7, author: "Bob", text: "Отличная статья!" },
  { id: 8, author: "Bob", text: "Отличная статья!" },
  { id: 9, author: "Bob", text: "Отличная статья!" },
  { id: 1, author: "John", text: "Крутой пост!" },
  { id: 2, author: "Jane", text: "Согласен с тобой!" },
  { id: 3, author: "Bob", text: "Отличная статья!" },
  { id: 4, author: "Bob", text: "Отличная статья!" },
  { id: 5, author: "Bob", text: "Отличная статья!" },
  { id: 6, author: "Bob", text: "Отличная статья!" },
  { id: 7, author: "Bob", text: "Отличная статья!" },
  { id: 8, author: "Bob", text: "Отличная статья!" },
  { id: 9, author: "Bob", text: "Отличная статья!" },
];